### ISSUE TITLE
fastboot flash response {"error":{"killed":false,"code":1,"signal":null,"cmd":"fastboot flash boot 'some.img'"},"stdout":"","stderr":"fastboot: error: Couldn't parse partition size '0x'.\n"} gets interpreted as oem lock

### ISSUE THREAD

**Issue by ressanoid** [ubports/ubports-installer#1368]
*Automatically generated error report* 
UBports Installer Version: 0.4.19-beta 
Device: kagura
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/hybris/stable","wipe":false,"bootstrap":true}
Package: dmg
Operating System: macOS 10.15.619G2021 x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/PmSVm4SMTT/ 
Sony Xperia XZ  
the device is already unlocked but it keeps on saying it's locked in the installer
![image](https://user-images.githubusercontent.com/15714267/94160437-47ff9f00-fe8d-11ea-884b-6ae5f83e0723.png)

**Comment by NeoTheThird** [comment]
Ah, i see you already opened another issue with the log, great, thanks! So there's two issues here: On the one hand, the unnecessary unlock fails (#1327). A fix for that is already lined up for the next release and awaiting review. Then, for some reason the `fastboot: error: Couldn't parse partition size '0x'.\n` in stderr gets interpreted as the device being OEM locked, which is the actual issue here. Thanks for reporting, i'll look at that now.

**Comment by NeoTheThird** [comment]
By the way, is the device running Android 8? Looking at the [config](https://github.com/ubports/installer-configs/blob/dfff8731924e124ac4fedb9f410696c20f094634/v1/kagura.json#L30) (since i don't have the device here), i see you will have been prompted with "If the device is running Android, should upgrade to Android 8.0 first.". Did you do that?

**Comment by NeoTheThird** [comment]
Such a stupid issue. We did the lock check by looking for "lock" in the error message, but the error message includes the filename as well. so if if the filename is halium_unlocked_recovery... :D that's what you get for being lazy. Anyways, PRs are lined up and should be included in the next release.

**Comment by ressanoid** [comment]
@NeoTheThird  yes the device is using android 8 stock firmware

**Comment by NeoTheThird** [comment]
@ressanoid could you try with the latest prerelease? https://github.com/ubports/ubports-installer/releases/tag/0.4.20-beta

**Comment by ressanoid** [comment]
@NeoTheThird this is what I got right now
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: kagura
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/hybris/stable","wipe":true,"bootstrap":true}
Package: dmg
Operating System: macOS 10.15.619G2021 x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/WcH5rTfsCK/

**Comment by NeoTheThird** [comment]
Thanks, let's track that in #1380
