### ISSUE TITLE
Package as a snap

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#14]
It would be nice to package this as a snap, just for the nerd-cred.

**Comment by tim-sueberkrueb** [comment]
Hey, looks like there is already snap packaging in the `snapcraft` folder, or am I missing something?

Two questions:
* Is there a specific reason for using `snapcraft/snapcraft.yaml` instead of `snap/snapcraft.yaml` and `source: <git url>` instead of `source: .`?
* What about building it automatically with [build.snapcraft.io](https://build.snapcraft.io/) or are you even already using your own infrastructure?

It also looks like electron builder supports snaps now: https://www.electron.build/configuration/snap.

**Comment by NeoTheThird** [comment]
Indeed, some work is already done, but looks like it hasn't been touched in a while. This issue is more about the infrastructure, and a reminder to fiddle with it.
