### ISSUE TITLE
[FP2] Instructions to get into Recovery do not work as displayed

### ISSUE THREAD

**Issue by jonnius** [ubports/ubports-installer#1436]
**UBports Installer `0.5.3-beta` (AppImage)**
Environment: `Ubuntu 20.04.1 LTS Focal Fossa linux 5.4.0-48-generic x64` with Node.js `v12.16.3`
Device: FP2
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f7f631d04d6b6000750ad8d
Log: https://paste.ubuntu.com//

![grafik](https://user-images.githubusercontent.com/4456588/95502995-fd147a00-09aa-11eb-9bc4-070df07e7f33.png)

1. The **Cleaning up...** and **Erasing cache partition** labels indicate that something is ongoing, which is not the case
1. I see instructions to press buttons and a **Continue** button to click at the same time. It is not clear what to do first.  
1. At that point the phone "hangs" at the Fairphone Boot splash screen. I have to long press power off to turn the device off with. Is this state avoidable? 
1. As long as the cable is connect I cannot get into recovery. The phone always boots into the charging animation. At least a hint for the user would be nice to temporarily disconnect the USB cable.

**Comment by NeoTheThird** [comment]
> The Cleaning up... and Erasing cache partition labels indicate that something is ongoing, which is not the case

Reported in #1426 

> I see instructions to press buttons and a Continue button to click at the same time. It is not clear what to do first.

I don't know if that's really an issue, because it doesn't matter what you do first. If you click the button, the installer will scan for adb connections. If there isn't one, it'll complain until you reboot to recovery. What do you propose? changing the button text?

> At that point the phone "hangs" at the Fairphone Boot splash screen. I have to long press power off to turn the device off with. Is this state avoidable?

This is a perfect example of the device-specific fuckery going on in the Android world. What you're seeing looks like the bootsplash, but it is in fact the fastboot mode. Not every device has a menu there, unfortunately. Additionally, the FP2 does not support the `fastboot boot boot.img` command, which makes this user action necessary. I opened #1440 for further investigation into a possible workaround.

> As long as the cable is connect I cannot get into recovery. The phone always boots into the charging animation. At least a hint for the user would be nice to temporarily disconnect the USB cable.

We can certainly add a hint there.

**Comment by NeoTheThird** [comment]
Alright, i [changed the text a little](https://github.com/ubports/installer-configs/commit/d4c69204f99c1260fc8e82161350a5e0b6cad4fd), let me know what you think. If you have suggestions for improvements, feel free to open a PR over there, or re-open this issue for further discussion. Thanks!

**Comment by jonnius** [comment]
The change is good. :+1:
