### ISSUE TITLE
Update available when using latest beta

### ISSUE THREAD

**Issue by jonnius** [ubports/ubports-installer#1437]
**UBports Installer `0.5.3-beta` (AppImage)**
Environment: `Ubuntu 20.04.1 LTS Focal Fossa linux 5.4.0-48-generic x64` with Node.js `v12.16.3`
Device: FP2
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f7f631d04d6b6000750ad8d
Log: https://paste.ubuntu.com//

![grafik](https://user-images.githubusercontent.com/4456588/95503953-621c9f80-09ac-11eb-8d52-9410d17d4a17.png)

How can an update be available while I use the latest beta?

**Comment by NeoTheThird** [comment]
right, that should probably say "prerelease" instead

**Comment by NeoTheThird** [comment]
I'm keeping this open, as it's a non-critical issue that is a good place to start for new contributors to understand the structure of the source code, especially how we make use of Electron's inter-process-communication.

This could easily be done by doing a size comparison rather than an equality comparison [in the update check](https://github.com/ubports/ubports-installer/blob/b9b699ff676405e6058ef1f9cb4f428f1b9d6b23/src/utils.js#L83), sending some information about whether the latest stable is newer or older than what is running along with [the signal](https://github.com/ubports/ubports-installer/blob/915eae451042466128383388ab2edfde4e89012f/src/report.js#L37) and [processing that information appropriately](https://github.com/ubports/ubports-installer/blob/915eae451042466128383388ab2edfde4e89012f/src/pug/modals/new-update.pug#L16) in the rendering process.
