### ISSUE TITLE
Support of multiple conditions

### ISSUE THREAD

**Issue by Vince1171** [ubports/ubports-installer#1536]
It'd be wonderful to be able to have multiple conditions in an array
something like that
```
{
    "type": "adb:sideload",
    "condition": [
       {"var": "gapps", "value": true},
       {"var": "LineageVersion", "value": "16"}
    ],
    "file": "open_gapps-arm64-9.0-nano-20200615.zip",
    "group": "OpenGApps"
},
{
   "type": "adb:sideload",
   "condition": [
      {"var": "gapps", "value": true},
      {"var": "LineageVersion", "value": "17"}
   ],
    "file": "open_gapps-arm64-10.0-nano-20200615.zip",
    "group": "OpenGApps"
}
```

**Comment by NeoTheThird** [comment]
I've thought about this a little already, the problem is that to be really flexible enough, you would need to be able to include both and and or operators and maybe even nested expressions. We might be able to steal some ideas from OPEN-CUTS' combination filtering language and support all boolean expressions: 

![image](https://user-images.githubusercontent.com/12068939/99086109-59317600-25c9-11eb-983b-1815df272d15.png)

some tweaks will be needed, since we don't need a first-order logic but just boolean algebra, but it should be doable.

**Comment by NeoTheThird** [comment]
How about the following structure for [v2](https://github.com/ubports/installer-configs/pull/51)?

```yml
AND:
  - var: "a"
    value: true
  - OR:
    - var: "b"
      value: 1
    - var: "b"
      value: 2
  - NOT:
      var: "c"
      value: 1337
```

This would be equivalent to
![image](https://user-images.githubusercontent.com/12068939/100104995-24de7500-2e67-11eb-9a99-90c38dfef641.png)

This allows all of algebra expression. We can add more syntax sugar down the road for convenience.

**Comment by Vince1171** [comment]
LGTM :D 
It's an "easy to use, but powerful" syntax
