### ISSUE TITLE
[snap] Manual download page does not offer a file selector

### ISSUE THREAD

**Issue by jonnius** [ubports/ubports-installer#1544]
**UBports Installer `0.7.2-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-53-generic x64 NodeJS v12.16.3`
Device: suzu
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5faf8def9702a600079dc75d
Log: https://paste.ubuntu.com/p/F3jvMMTqRr/

A simple textfield to past a path in does not fit into the overall UI. There should be a file selector at least.

**Comment by NeoTheThird** [comment]
Currently waiting for electron to add support for xdg desktop portals (https://github.com/electron/electron/pull/19159), so we can show the system file picker on snap. If you try opening the dialog in a confined snap as-is, apparmor will kill you dead. I agree, the current way is not great, but it gets the job done. Since an upstream fix is expected soon, i'd rather not create a hacky workaround on our side.
