### ISSUE TITLE
after installation screen is black. after reboot - nothing loads (xiaomi redmi 4x)

### ISSUE THREAD

**Issue by mishatron** [ubports/ubports-installer#1689]
**UBports Installer `0.8.2-beta` (exe)**
Environment: `�������� Windows 10 Pro 10.0.19041 win32 10.0.19041 x64 19041 0.0 NodeJS v12.16.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

install to xiaomi redmi 4x stable or develop branch

**Comment by GeorgeKitsopoulos** [comment]
Tried to install every channel but failed. I do not think it's the installers fault though as it failed to update even before reflashing.
Same Santoni/redmi 4x
Installer: deb on pop os 20.4 - latest version

**Comment by GeorgeKitsopoulos** [comment]
> Tried to install every channel but failed. I do not think it's the installers fault though as it failed to update even before reflashing.
> Same Santoni/redmi 4x
> Installer: deb on pop os 20.4 - latest version

ok tried again today and it works again. Haven't tried all the channels yet.

**Comment by Danct12** [comment]
This issue is now reported here: https://github.com/ubports/ubuntu-touch/issues/1695

**Comment by UniversalSuperBox** [comment]
Hi, the UBports Recovery is currently unable to boot on some Redmi 4X devices. You can find more information about this issue here: ubports/ubuntu-touch#1695.

Since this issue is filed in a more relevant place, please continue any further discussion at ubports/ubuntu-touch#1695. I'll close this issue to help us know what work still needs to be done.
