### ISSUE TITLE
After install, the phone reboots. I see Mi logo and after that only blank screen.

### ISSUE THREAD

**Issue by Adamyno** [ubports/ubports-installer#1820]
**UBports Installer `0.8.5-beta` (AppImage)**
Environment: `ManjaroLinux 20.2.1 Nibia linux 5.4.100-1-MANJARO x64 rolling NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/603fa2a36bfdd00007c8814d
Log: *N/A*

Only install and reboot automatically.

**Comment by Danct12** [comment]
This issue is now reported here: https://github.com/ubports/ubuntu-touch/issues/1695

**Comment by UniversalSuperBox** [comment]
Hi, the UBports Recovery is currently unable to boot on some Redmi 4X devices. You can find more information about this issue here: ubports/ubuntu-touch#1695.

Since this issue is already filed, please continue any further discussion at ubports/ubuntu-touch#1695. I'll close this issue to help us know what work still needs to be done.
