### ISSUE TITLE
edge and stable doesn't work, stucks at initial boot during the boot logo

### ISSUE THREAD

**Issue by StardockMW** [ubports/ubports-installer#1856]
**UBports Installer `0.8.5-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/604e89e7b4f6d800072ee5bb
Log: *N/A*

installling edge or stable branch

**Comment by UniversalSuperBox** [comment]
Hi @StardockMW, the UBports Recovery is currently unable to boot on some Redmi 4X devices. You can find more information about this issue here: ubports/ubuntu-touch#1695.

Since this issue is already filed, please continue any further discussion at ubports/ubuntu-touch#1695. I'll close this issue to help us know what work still needs to be done.
