### ISSUE TITLE
OS is not booting

### ISSUE THREAD

**Issue by JacquesSchreiber** [ubports/ubports-installer#1857]
**UBports Installer `0.8.7-beta` (deb)**
Environment: `Ubuntu 20.04.2 LTS Focal Fossa linux 5.8.0-44-generic x64 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/604f2834b4f6d800072ee727
Log: *N/A*

Install latest stable release and reboot phone

**Error:**
```
OS is not booting
```

**Comment by UniversalSuperBox** [comment]
Hi @JacquesSchreiber, the UBports Recovery is currently unable to boot on some Redmi 4X devices. You can find more information about this issue here: ubports/ubuntu-touch#1695.

Since this issue is already filed, please continue any further discussion at ubports/ubuntu-touch#1695. I'll close this issue to help us know what work still needs to be done.
