### ISSUE TITLE
Ubports installer stucks in sending utouch files to device

### ISSUE THREAD

**Issue by stoi2000** [ubports/ubports-installer#1858]
**UBports Installer `0.8.7-beta` (deb)**
Environment: `Ubuntu 20.04.2 LTS Focal Fossa linux 5.4.0-67-generic x64 NodeJS v12.18.3`
Device: kugo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6050aa5c2c9f6900077e1553
Log: *N/A*

Sony Xperia X compact with Android 8.0.0 preinstalled and working // adb installed

Logfile

Mar 16 13:53:48 X240 kernel: [ 2918.393254] usb 2-2: new high-speed USB device number 56 using xhci_hcd
Mar 16 13:53:49 X240 kernel: [ 2918.543760] usb 2-2: New USB device found, idVendor=0fce, idProduct=71e8, bcdDevice= 4.04
Mar 16 13:53:49 X240 kernel: [ 2918.543769] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Mar 16 13:53:49 X240 kernel: [ 2918.543773] usb 2-2: Product: Xperia X Compact
Mar 16 13:53:49 X240 kernel: [ 2918.543775] usb 2-2: Manufacturer: Sony
Mar 16 13:53:49 X240 kernel: [ 2918.543777] usb 2-2: SerialNumber: BH905RMD5Z
Mar 16 13:53:49 X240 mtp-probe: checking bus 2, device 56: "/sys/devices/pci0000:00/0000:00:14.0/usb2/2-2"
Mar 16 13:53:49 X240 mtp-probe: bus: 2, device: 56 was not an MTP device
Mar 16 13:53:49 X240 mtp-probe: checking bus 2, device 56: "/sys/devices/pci0000:00/0000:00:14.0/usb2/2-2"
Mar 16 13:53:49 X240 mtp-probe: bus: 2, device: 56 was not an MTP device

**Comment by UniversalSuperBox** [comment]
Hi @stoi2000,

The most common cause of this problem is udev rules being incorrect or not being installed on the device you are installing Ubuntu Touch with. This seems even more likely since you had to select the device manually instead of it being automatically detected. You can find more information about this problem at https://docs.ubports.com/en/latest/userguide/install.html#missing-udev-rules.

Please let us know if this issue continues on installer version 0.8.8 and with the correct udev rules in place on your system.

Since this report is so long without a response, I will close it. I'm happy to reopen if you're still having this problem, though. Just let me know.
