### ISSUE TITLE
FP2 not detected despite it is detected - split brain?

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubports-installer#187]
Left part of screenshot: property is successfully loaded from device. Right part: Waiting for device?
![grafik](https://user-images.githubusercontent.com/16186470/38467203-32a6b1ac-3b35-11e8-85c5-d43a220b51af.png)

**Comment by Flohack74** [comment]
Additional info: The device was connected already when ubports installer was started. Problem went away when closing installer, unplugging the device and then plugging it back in when the installer was started.

**Comment by gsilvapt** [comment]
Hi @Flohack74.

I think that plugging the device after executing the installer is a required step, although it is not explicitly mentioned in the installer. We can try making it more dynamic in that regard. Or explicitly mention in the guides we have available. At least the YouTube video of the Nexus 5, the person clearly shows that.

**Comment by Flohack74** [comment]
It is not obvious that the device should be disconnected, and I think the small state machine can be extended to cover that case. Can you take a look?

**Comment by gsilvapt** [comment]
Okay, I misunderstood this problem a bit. I thought it was not working at all despite being connected and the terminal telling you so. I think we can assume the page is not changing when the device is connect. I guess I have to find where this is happening and add this validation.

**Comment by gsilvapt** [comment]
And I actually am experiencing the same issue. I can choose the device manually but the installer does not recognize the device automatically. Hopefully me and @NeoTheThird will be able to find a solution to this.

**Comment by Flohack74** [comment]
Maybe this is bothering many people already, we are getting frequent reports of a device being not detected :)

**Comment by gsilvapt** [comment]
Indeed. I was wondering how reliable the system is. It didn't recognize my device manually but I thought it was okay considering the installation process went flawlessly. 

Anyway, this is definitely a priority to solve. We have to ensure this part of the installation process is working as we want to.

**Comment by Ingo-FP-Angel** [comment]
I can add my observation from trying 0.1.20-beta just now (snap on Opensuse Leap 42.3). Two tries were needed in my case

1. Start the installer -> connect the FP2 -> terminal detects fine, UI still in "please connect via USB" (this bug here)
2. Close the installer -> leave the FP2 connected -> start the installer again -> all works as expected

**Comment by NeoTheThird** [comment]
So the issue here is that the signal is sent correctly, but the event is not ready to receive it yet. Fixing this with the current setup would be a little hacky. Since the user can easily work around the issue by selecting the device manually, i won't work on this for now. It'll resolve itself when we move to the new modules and the promise pipeline (#58). Will probably happen some time this summer.

If someone else wants to look into it before, that's fine as well :)

**Comment by Flohack74** [comment]
Hint for event race-conditions: Upon connecting to an event, read the current state additionally one time ;)

**Comment by NeoTheThird** [comment]
Yeah. But as i said, we're replacing the event system anyways, so *I* won't do any fixing on non-critical issues for now.
