### ISSUE TITLE
UBPorts installer 0.8.7 won't connect to server. In 0.8.6 is all fine.

### ISSUE THREAD

**Issue by liss21** [ubports/ubports-installer#1884]
**UBports Installer `0.8.7-beta` (exe)**
Environment: ` Windows 10  10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: GT-I9301I
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6062d38b7977a000070f5e0c
Log: https://paste.ubuntu.com/p/7Mtbjb7K3w/

Launch UBP Installer 0.8.7.

**Comment by joukonature** [comment]
Trying to do my first linux phone from nexus 6.  Cannot get the UBports installer 0.8.7 working. First the problem was : Cannot find the server,,, check your proxy... I don't know what it means as internet works totally 100%. Changed anyway to Quad 9.9.9.9 but still it stops to following.. win10 latest PC.

The Installation stopped due to a problem. You can choose to ignore this, or re-start the installation process.
If this continues to happen, please check if you are affected by a known bug.
If your problem is not yet known, click the button below to report a new bug.
Error: unhandled rejection at [object Promise]: Error: {"error":{"code":1,"cmd"

**Comment by rob-patchett** [comment]
Same issue here - tested on two separate Macs (one running macOS 11, the other 10.11).

**Comment by UniversalSuperBox** [comment]
Hi everyone, thanks for letting us know you had a problem with the UBports Installer. It sounds like you're running into #1847, and I've added information to work around the problem there.

I'll close this issue report to keep the issue tracker cleaner and help us know what work we need to do.
