### ISSUE TITLE
Error, phone lock in fastboot

### ISSUE THREAD

**Issue by MrsMagoo** [ubports/ubports-installer#1885]
**UBports Installer `0.8.7-beta` (deb)**
Environment: `Pop 20.10 groovy linux 5.8.0-7642-generic x64 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6063b9cf318b030007fc53dd
Log: https://paste.ubuntu.com/p/mRHDzk5dQh/

after flash firmware, phone not reboot and lock in fastboot, in status "Wait for Adb devices"

**Comment by Danct12** [comment]
Might be this issue: https://github.com/ubports/ubuntu-touch/issues/1695

**Comment by UniversalSuperBox** [comment]
Hi, the UBports Recovery is currently unable to boot on some Redmi 4X devices. You can find more information about this issue here: ubports/ubuntu-touch#1695.

Since this issue is already filed, please continue any further discussion at ubports/ubuntu-touch#1695. I'll close this issue to help us know what work still needs to be done.
