### ISSUE TITLE
Redmi 4X frozen on Ubuntu Touch found. boot title.

### ISSUE THREAD

**Issue by Raphaey** [ubports/ubports-installer#1901]
**UBports Installer `0.8.7-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-48-generic x64 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/606db97c7327390007b9d816
Log: *N/A*

My device is frozen on the Ubuntu Touch Found. boot title. I can't access to any setting, I only have access to the fastboot command to try again the install process or another one... my device is unusable at this moment.

**Comment by UniversalSuperBox** [comment]
Hi @Raphaey,

The UBports Recovery is currently unable to boot on some Redmi 4X devices. You can find more information about this issue here: https://github.com/ubports/ubuntu-touch/issues/1695.

Since this issue is already filed, please continue any further discussion at https://github.com/ubports/ubuntu-touch/issues/1695. I'll close this issue to help us know what work still needs to be done.
