### ISSUE TITLE
Could not connect to UBports server, start adb sever or find codename.

### ISSUE THREAD

**Issue by oddlander** [ubports/ubports-installer#1918]
**UBports Installer `0.8.7-beta` (exe)**
Environment: `Microsoft Windows 10 Pro N 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/607c4327f5ba7600078594af
Log: *N/A*

Just run the installer on win 10.
I started adb sever manualy, and ignored the "could not find codename"

**Comment by oddlander** [comment]
I don't my ubuntu computer at hand right now, but I'll try to install Ubuntu Touch on my santoni phone using that instead.

**Comment by UniversalSuperBox** [comment]
Hi, thanks for letting us know you had a problem with the UBports Installer. It sounds like you ran, and I've added information to work around the problem there.

I'll close this issue report to keep the issue tracker cleaner and help us know what work we need to do.

Additionally, the UBports Recovery is currently unable to boot on some Redmi 4X devices. You can find more information about this issue here: ubports/ubuntu-touch#1695.

If that is the issue you are experiencing, please continue any further discussion at ubports/ubuntu-touch#1695. I'll close this issue to help us know what work still needs to be done.
