### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 1073741824 bytessending 'recovery' (11802 KB)...OKAY [  0.585s]writing 'recovery'...FAILED (remote: flash write failure)finished. total time: 0.765s

### ISSUE THREAD

**Issue by cyberbra1n** [ubports/ubports-installer#202]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux undefined
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/J2KrxSg6Ss/

**Comment by NeoTheThird** [comment]
What device is this, and what OS is it running? This might be a case of #221.

**Comment by cyberbra1n** [comment]
Hello Jan,

Device is nexus 5 hammerhead,
It had installed UbPort's Ubuntu Touch, but it broke at some point and
didn't want to boot.
So I've entered recovery mode, and tried to clean my partitions but
unsuccessfully...getting error 'max download size'.
I've also tried with another recovery mode, and fastboot...but also
unsuccessfully.
Is there a possibility that this is hardware issue (flash memory died or
something like that)?

Thanks for your response.

**Comment by NeoTheThird** [comment]
Okay, so the installer won't always be able to unbrick devices, but you might be able to fix your device with [a guide like this](https://androidcure.com/unbrick-google-nexus-5/). Do some research and try different things. If nothing works, it might be a hardware issue.

What exactly do you mean by "it broke and at some point it wouldn't boot"? With normal use, it's very uncommon for Ubuntu Touch to cause a brick.

Closing this, since it's beyond the scope of the installer.
