### ISSUE TITLE
Uncaught Error: EACCES: permission denied, open '/home/u5/.cache/ubports/commandfile/ubuntu_commandFP27158' (MainRenderer:652)

### ISSUE THREAD

**Issue by GeorgSimon** [ubports/ubports-installer#212]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/xrGPbJ7Vvs/

**Comment by NeoTheThird** [comment]
Could you get me the output of `ls -Rl /home/u5/.cache/ubports`?

**Comment by GeorgSimon** [comment]
https://paste.ubuntu.com/p/MZqCQZkTxS/
Meanwhile my Ubuntu Touch works.
I had to add vendor ID in adb_usb.ini : https://t.me/ubports/123664
As it seems it is important
- to power off the Fairphone and
- to start ubports-installer with sudo

**Comment by NeoTheThird** [comment]
Yeah, so that's the problem right there. You definitely do not need to run the installer with sudo, as a result of doing that, the files in the cache folder are now owned by root, and not you. Run `sudo chown -R $USER ~/.cache/ubports` to fix that. From now on, you will not have to use sudo. If the installer needs elevated privilleges to run a task, it will ask you for the password itself. The hint for the vendor-ID is correct, even though that is for example not necessary in the snap.
