### ISSUE TITLE
При выборе удаления пользовательской информации смартфон перезагружается и далее ничего не происходит

### ISSUE THREAD

**Issue by dertaster** [ubports/ubports-installer#2133]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/614f5b951653920008ab1a24
Log: *N/A*

IDK

**Comment by NotKit** [comment]
Does fastboot tool in general work on that machine? It can be checked by running `fastboot devices` when device is in fastboot mode. Can be a problem due to missing drivers on Windows.

Установлены ли драйвера для fastboot на ПК? Можно проверить, выполнив fastboot devices в командной строке (подробнее - https://4pda.to/forum/index.php?showtopic=383300).

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
