### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by JollyRoger91** [ubports/ubports-installer#2201]
**UBports Installer `0.9.1-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v16.5.0`
Device: miatoll
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6167faa8a5d4010008a9f7b6

**Error:**
```
Unknown Error
```

I'm trying to install UbuntuTouch/UBPorts on my **Xiaomi Redmi Note 9s**, without any success.

Also with the [**V0.8.8**](https://gitlab.com/ubports/community-ports/android10/xiaomi-redmi-note-9-pro/xiaomi-miatoll/-/issues/3) Version of the UBPorts-Installer it fails constantly to install. 

Is there any known problem with this device currently?

I would appreciate any help. Thanks! 

The following error occures:
`
Error: adb:preparesystemimage: Error: {"error":{"code":126,"cmd":"C:\\Users\\UserX~1\\AppData\\Local\\Temp\\1z2CZhpznORyjIPpqvVgfFBXFGZ\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 shell mkdir -p /cache/recovery"},"stderr":"error: Exec '/system/bin/sh' failed: No such file or directory"}
`

**Comment by phiibuntu** [comment]
Hi, same here with V0.8.8 or V0.9.1 ubports installer (on Windows 10 or ubuntu 20.04) 
With more try the best I had was a boot loop.

**Comment by zubozrout** [comment]
Well, it seems the problem is still not resolved, likely because the recovery doesn't have "/system/bin/sh"?

Meaning, the recovery linked here: https://raw.githubusercontent.com/ubports/installer-configs/2bc56419e02e572ac809477aaab8c72f56f52932/v2/devices/miatoll.yml
that is this one: https://github.com/ubuntu-touch-miatoll/ubuntu-touch-miatoll/releases/download/stable/recovery.img

when flashed I can't use `adb shell` as when I do I get the following error: `error: Exec '/system/bin/sh' failed: No such file or directory` and won't get in.

And that seems to also affect the installation process. Any thoughts/ideas @nitanmarcel?

Ps. The stable recovery linked here: https://github.com/ubuntu-touch-miatoll/ubuntu-touch-miatoll/releases (3e5d823) fortunately seems to work.
Thank you

**Comment by zubozrout** [comment]
Sorry for my previous post. That is incorrect, and I didn't realize you are actually linking to "stable" in the miatoll.yml, despite me copying it over above. However the issue is still exactly the same for me as reported, indeed weird :'(:
```
info: Installing Ubuntu Touch on your Xiaomi Redmi Note 9 Pro/Pro Max/9S - Poco M2 Pro (miatoll)
info: configuring...
info: settings: {"channel":"16.04/arm64/android9/stable","wipe":false,"bootstrap":true}
info: Downloading 9 files
info: Downloaded file 1 of 9
[...]
info: Downloaded file 9 of 9
error: Error: adb:preparesystemimage: Error: {"error":{"code":126,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"error: Exec '/system/bin/sh' failed: No such file or directory"}
stack trace: Error: {"error":{"code":126,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"error: Exec '/system/bin/sh' failed: No such file or directory"}
```

**Comment by nitanmarcel** [comment]
> Sorry for my previous post. That is incorrect, and I didn't realize you are actually linking to "stable" in the miatoll.yml, despite me copying it over above. However the issue is still exactly the same for me as reported, indeed weird :'(:
> 
> ```
> info: Installing Ubuntu Touch on your Xiaomi Redmi Note 9 Pro/Pro Max/9S - Poco M2 Pro (miatoll)
> info: configuring...
> info: settings: {"channel":"16.04/arm64/android9/stable","wipe":false,"bootstrap":true}
> info: Downloading 9 files
> info: Downloaded file 1 of 9
> [...]
> info: Downloaded file 9 of 9
> error: Error: adb:preparesystemimage: Error: {"error":{"code":126,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"error: Exec '/system/bin/sh' failed: No such file or directory"}
> stack trace: Error: {"error":{"code":126,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"error: Exec '/system/bin/sh' failed: No such file or directory"}
> ```

Known issue with the installer https://github.com/ubports/ubports-installer/issues/2147

The fix is to revert once again back to stock and run the installer again.

**Comment by zubozrout** [comment]
Thank you very much for the info @nitanmarcel.
I was just looking into that more closely and even when using the correct  recovery and removing all the redundant steps in the installer config, the `systemimage:install` indeed seems to fail.
I would not have tried reinstalling anything but unfortunately I got stuck with system images broken just recently, no idea why:
https://github.com/ubports/ubuntu-touch/issues/314 (`No such file or directory: '/android/cache/recovery'`)

Also, I don't want to do a full reinstall as suggested, that sounds too depressing to do whenever needed, as that would delete all my data and settings. So I did cloned the repo, commented out `// .then(() => this.adb.shell("mount -a").catch(() => null))` in the plugin.js as outlined and it does indeed behave differently. I even get to this point, where it says:

```
info: All done! Your device will now reboot and complete the installation. Enjoy exploring Ubuntu Touch!
```
However, it then just reboots to recovery again and sits there. And when I reboot to system the update doesn't seem to be applied, e.g. when I flash stable on devel, it is still devel.

**Comment by zubozrout** [comment]
So after trying to figure out what could be missing there I ended up doing touch `mkdir /android/cache/recovery`, as that was actually responsible for the failed update downloads - https://gitlab.com/ubports/core/system-image/-/issues/16. However, when rebooting it still just enters recovery and sits there forever, no updates applied. Same as with the installer ^.

First of all though, `sudo system-image-cli --switch 16.04/arm64/android9/devel --progress=dots` or stable/rc (doesn't matter) seems to end up with: `Exception occurred during update; see log file for details`, and client.log ends with:
```
FileNotFoundError: http://system-image.ubports.com/pool/ubports-af164540a9a1ff41694375d6f4af9e485b3d0e7f0094c2b5139776c316bcb51a.tar.xz:HASH ERROR
```
Sadly I have no idea why.

Looking at "ubuntu_updater.log" in the recovery, I can also see:
```
Applying update: ubports-[...].delta-ubports-[...].tar.xz
mv: bad 'data/*': No such file or directory
```

Initially `/dev/block/bootdevice/by-name/userdata` is not mounted to `/data`, but when I do that manually it works. On the other end, "System Image Upgrader" should be mounting that on its own and it does so when I execute it.

Anyway, I am quite diverting here now as that is unrelated to the reported issue.

**Comment by nitanmarcel** [comment]
> Thank you very much for the info @nitanmarcel. I was just looking into that more closely and even when using the correct recovery and removing all the redundant steps in the installer config, the `systemimage:install` indeed seems to fail. I would not have tried reinstalling anything but unfortunately I got stuck with system images broken just recently, no idea why: [ubports/ubuntu-touch#314](https://github.com/ubports/ubuntu-touch/issues/314) (`No such file or directory: '/android/cache/recovery'`)
> 
> Also, I don't want to do a full reinstall as suggested, that sounds too depressing to do whenever needed, as that would delete all my data and settings. So I did cloned the repo, commented out `// .then(() => this.adb.shell("mount -a").catch(() => null))` in the plugin.js as outlined and it does indeed behave differently. I even get to this point, where it says:
> 
> ```
> info: All done! Your device will now reboot and complete the installation. Enjoy exploring Ubuntu Touch!
> ```
> 
> However, it then just reboots to recovery again and sits there. And when I reboot to system the update doesn't seem to be applied, e.g. when I flash stable on devel, it is still devel.

Oh. You don't need to run the installation again to change the update channel. You can do that from Settings -> Updates -> Gear Icon -> Channels.

The fix for the issue is explained on the issue link I posted above.

**Comment by zubozrout** [comment]
Correct @nitanmarcel, and I have attempted that many times but it always failed, firstly likely because of some error on the userdata partition which took a while to pinpoint. It mounted just fine, but the system installer in UT recovery failed on that. In addition to that system updates started giving me "HASH ERROR" when trying to download an update. And reinstalling UT with the UT installer (without wiping data or anything extensive) still seems to be a no-go, the recovery just won't apply the update. What's more, when trying UT installer again I was back at step one: `No such file or directory: '/android/cache/recovery'` given because `system-image-cli` or its UI inside system settings doesn't seem to have a folder to store the update in.

What I also found is this [mount-android.conf](https://gitlab.com/ubports/community-ports/android10/xiaomi-redmi-note-9-pro/xiaomi-miatoll/-/blob/halium-10.0/overlay/system/etc/init/mount-android.conf) file which seems to be doing something with that cache partition. Also when I re-run `mount -o bind /userdata/cache /android/cache` the `/android/cache/recovery` directory appears and also system update finally works. phew ...

So other than perhaps the `e2fsck` required to make the system-updater in recovery work it seems to also be something related to incorrect partition being mounted in /cache, hence the "recovery" folder inside missing and perhaps also that making all the other bits uncooperative. Though still weird UT installer didn't cope with that and it didn't fix the issue :(.

Well, this was very interesting, also no idea what is/was going on.

**Comment by zubozrout** [comment]
Hi @nitanmarcel,
sorry to bother you once more, but after today's devel update my phone stayed on the bootloader screen. So actually had to give a reinstall via an UBports installer a go and had to make it work.

The things I could observe so far and to sum them up:

1. You are [mounting a different cache partition](https://gitlab.com/ubports/community-ports/android10/xiaomi-redmi-note-9-pro/xiaomi-miatoll/-/blob/halium-10.0/overlay/system/etc/init/mount-android.conf).
2. This is not working in the recovery, at least not for me for some reason. I mean it can install system updates, but when working with the UBports installer that pushes the update to the device while the recovery is running, I actually had to use the [TWRP](https://forum.xda-developers.com/t/recovery-3-4-0-14-miatoll-twrp-xiaomi-redmi-note-9s-9-pro-9-pro-max-poco-m2-pro.4125487) recovery as `/userdata` can't be mounted in the UT recovery because of the kernel error in point 1.
3. When I load TWRP, update the [installer's device installer config](https://raw.githubusercontent.com/ubports/installer-configs/2bc56419e02e572ac809477aaab8c72f56f52932/v2/devices/miatoll.yml) to only start with `systemimage:install` and tweak [plugin.js](https://github.com/ubports/ubports-installer/blob/31f330b828b727a16c2766fa52bb08b6384babc8/src/core/plugins/systemimage/plugin.js) to do adb push here: `dest: "/data/cache/recovery"` I can make the updates work. It pushes everything in, reboots, then installed UT recovery picks the files up and installs the update.

If I would not apply these tweaks and just used UBport's native recovery, then it would push the files there just fine but recovery would not pick them up upon second reboot to it (the update files would have been lost with the reboot) and it would just sit there indefinitely.

So I am very curious why do you think this all is the case and if it is just on my end? But this is I believe a different issue to `Make mount -a optional in systemimage:install action`.
Thank you

**Comment by nitanmarcel** [comment]
> Hi @nitanmarcel, sorry to bother you once more, but after today's devel update my phone stayed on the bootloader screen. So actually had to give a reinstall via an UBports installer a go and had to make it work.
> 
> The things I could observe so far and to sum them up:
> 
> 1. You are [mounting a different cache partition](https://gitlab.com/ubports/community-ports/android10/xiaomi-redmi-note-9-pro/xiaomi-miatoll/-/blob/halium-10.0/overlay/system/etc/init/mount-android.conf).
> 2. This is not working in the recovery, at least not for me for some reason. I mean it can install system updates, but when working with the UBports installer that pushes the update to the device while the recovery is running, I actually had to use the [TWRP](https://forum.xda-developers.com/t/recovery-3-4-0-14-miatoll-twrp-xiaomi-redmi-note-9s-9-pro-9-pro-max-poco-m2-pro.4125487) recovery as `/userdata` can't be mounted in the UT recovery because of the kernel error in point 1.
> 3. When I load TWRP, update the [installer's device installer config](https://raw.githubusercontent.com/ubports/installer-configs/2bc56419e02e572ac809477aaab8c72f56f52932/v2/devices/miatoll.yml) to only start with `systemimage:install` and tweak [plugin.js](https://github.com/ubports/ubports-installer/blob/31f330b828b727a16c2766fa52bb08b6384babc8/src/core/plugins/systemimage/plugin.js) to do adb push here: `dest: "/data/cache/recovery"` I can make the updates work. It pushes everything in, reboots, then installed UT recovery picks the files up and installs the update.
> 
> If I would not apply these tweaks and just used UBport's native recovery, then it would push the files there just fine but recovery would not pick them up upon second reboot to it (the update files would have been lost with the reboot) and it would just sit there indefinitely.
> 
> So I am very curious why do you think this all is the case and if it is just on my end? But this is I believe a different issue to `Make mount -a optional in systemimage:install action`. Thank you

The link you gave me is for the Ubuntu Touch system which works at is should. If it wouldn't you won't be able to update UT from the system settings. Has nothing to do with the recovery where the userdata partition is mounted correctly:

Here you can also see why the error: `Exec '/system/bin/sh' failed: No such file or directory"}`
![image](https://user-images.githubusercontent.com/41646249/153285915-74ecc6f4-3439-4513-a6e9-5ddb798936b3.png)

**Comment by nitanmarcel** [comment]
> Thank you very much for the info @nitanmarcel. I was just looking into that more closely and even when using the correct recovery and removing all the redundant steps in the installer config, the `systemimage:install` indeed seems to fail. I would not have tried reinstalling anything but unfortunately I got stuck with system images broken just recently, no idea why: [ubports/ubuntu-touch#314](https://github.com/ubports/ubuntu-touch/issues/314) (`No such file or directory: '/android/cache/recovery'`)
> 
> Also, I don't want to do a full reinstall as suggested, that sounds too depressing to do whenever needed, as that would delete all my data and settings. So I did cloned the repo, commented out `// .then(() => this.adb.shell("mount -a").catch(() => null))` in the plugin.js as outlined and it does indeed behave differently. I even get to this point, where it says:
> 
> ```
> info: All done! Your device will now reboot and complete the installation. Enjoy exploring Ubuntu Touch!
> ```
> 
> However, it then just reboots to recovery again and sits there. And when I reboot to system the update doesn't seem to be applied, e.g. when I flash stable on devel, it is still devel.

> So I did cloned the repo, commented out `// .then(() => this.adb.shell("mount -a").catch(() => null))`

Here you just have commented the only thing that takes care of mounting the system folder so the installer doesn't have where to copy it's files.

**Comment by nitanmarcel** [comment]
Also the `/data/cache/recovery` is also mounted properly.

You can view how the cache path is created in the recovery here:

https://gitlab.com/ubports/community-ports/android10/xiaomi-redmi-note-9-pro/xiaomi-miatoll/-/blob/halium-10.0/ramdisk-recovery-overlay/init.recovery.qcom.rc#L35
https://gitlab.com/ubports/community-ports/android10/xiaomi-redmi-note-9-pro/xiaomi-miatoll/-/blob/halium-10.0/ramdisk-recovery-overlay/setup_fake_cache.sh

![image](https://user-images.githubusercontent.com/41646249/153287179-a8ec7aea-cd7e-466d-9a01-c85145e60a17.png)

Please, don't make problems that don't exist. I'm sure that the mount issue will be fixed in the close future. Currently there's only one developer working on the installer so it's hard for him to focus only on the project :)

**Comment by nitanmarcel** [comment]
> Thank you very much for the info @nitanmarcel. I was just looking into that more closely and even when using the correct recovery and removing all the redundant steps in the installer config, the `systemimage:install` indeed seems to fail. I would not have tried reinstalling anything but unfortunately I got stuck with system images broken just recently, no idea why: [ubports/ubuntu-touch#314](https://github.com/ubports/ubuntu-touch/issues/314) (`No such file or directory: '/android/cache/recovery'`)
> 
> Also, I don't want to do a full reinstall as suggested, that sounds too depressing to do whenever needed, as that would delete all my data and settings. So I did cloned the repo, commented out `// .then(() => this.adb.shell("mount -a").catch(() => null))` in the plugin.js as outlined and it does indeed behave differently. I even get to this point, where it says:
> 
> ```
> info: All done! Your device will now reboot and complete the installation. Enjoy exploring Ubuntu Touch!
> ```
> 
> However, it then just reboots to recovery again and sits there. And when I reboot to system the update doesn't seem to be applied, e.g. when I flash stable on devel, it is still devel.

> Also, I don't want to do a full reinstall as suggested
> And when I reboot to system the update doesn't seem to be applied, e.g. when I flash stable on devel, it is still devel.

Looking again at the messages I figured out what you're trying to do and what you're doing.

As I said in https://github.com/ubports/ubports-installer/issues/2201#issuecomment-1030762059 you don't have to use the installer to change update channels, since it breaks if UT is already installed to the issues linked a couple of messages above.

You can change channels in no time from from `Settings -> Updates -> Gear Icon -> Channels`. If you get stuck at the loading channel connect to an wireless connection and try again.

![image](https://user-images.githubusercontent.com/41646249/153291350-41d20690-9442-4229-b1df-cb2167c55891.png)

![image](https://user-images.githubusercontent.com/41646249/153291197-39d5c15c-bd55-42a3-b45a-e8c6346510f3.png)

**Comment by zubozrout** [comment]
Sorry @nitanmarcel, I think we are not on the same wave here unfortunately. The reasons I am doing all these hacky things are:
1. I was unable to apply system updates. They would not download. But I was able to fix that fortunately by manually running `mount -o bind /userdata/cache /android/cache` before trying to download an install an update. That issue didn't reappear.
2. UBports installer doesn't work for me properly even if I workaround this issue as suggested: https://github.com/ubports/ubuntu-touch/issues/314

As noted, I know how to change channels (I am using UT since 2015), but if applying a system update is not an option (either it fails or the system doesn't even boot) then the installer is the only option I can reply on.

Unfortunately, the phone really started behaving weirdly to me today. And at this particular moment all I have is a boot logo and a recovery. So I am going to have to go the full reinstall way as currently the phone doesn't even boot. And since it for some reason doesn't work for me with UT native recovery even with the tweak from the 314 issue ^, I guess a jump to Android and then UT is all I have left. I mean I am able to fore it install an update via TWRP recovery (the one in UT does not seem to have everything mounted as it should, or at least doesn't work for me - and the fact I can run `mount /device /folder` nor mount anything listed in fstab directly is also very weird and indeed looks like a kernel support issue, at least based on what I could Google.

**Comment by zubozrout** [comment]
Hm, recovery including partition mounting started working properly after a full clean reinstall with Android install in the middle. So there must have definitely been something wrong there :(.

**Comment by BadAngelZ** [comment]
>     1. I was unable to apply system updates. They would not download. But I was able to fix that fortunately by manually running `mount -o bind /userdata/cache /android/cache` before trying to download an install an update. That issue didn't reappear.

Thanks for this workaround, it saved my day !
I had to run it mon my RedmiNote 7 which is on the release candidate channel, and show me the "FileNotFoundError: [Errno2] No such file or directory: '/android/cache/recovery" (same as here: https://github.com/ubports/ubuntu-touch/issues/314 )
After doing the mount, the update could be done from the phone.
