### ISSUE TITLE
ADB drivers installed but installer gives warning about no install of ADB drivers

### ISSUE THREAD

**Issue by igoratomubootski** [ubports/ubports-installer#247]
Notebook XMG P505 / OnePlus One with LineageOS 14.1
-Win 10 x64, newest
-USB 3

Installer says the ADB drivers must be installed but drivers are installed, phone is shown in my computer and data transfer is working.
So what is the problem with the UBports installer?
I would like to test the UBports but I have no idea what failure and how to solve.
THX for help!!!

**Comment by NeoTheThird** [comment]
The installer does not try to detect the drivers, it just displays an informative message if it's run on windows. That's expected behavior. Just dismiss the message and continue.

If you have a proposal to make [the message](https://github.com/ubports/ubports-installer/blob/master/src/html/modals/windows-drivers.pug#L10) easier to understand, feel free to send a PR.

**Comment by igoratomubootski** [comment]
THX for your fast answer.
Prost nach München!

**Comment by NeoTheThird** [comment]
🍺
