### ISSUE TITLE
Failed To Unlock Boot Loader

### ISSUE THREAD

**Issue by dtarrant2019** [ubports/ubports-installer#2535]
**UBports Installer `0.9.2-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-105-generic x64 NodeJS v16.13.0`
Device: [X605]
(https://devices.ubuntu-touch.io/device/X605)
Target OS: Ubuntu Touch
Settings: Developer mode enabled, also usb
OPEN-CUTS run: https://ubports.open-cuts.org/run/623ce60ebfb7110008fb43ae
Pastebin: https://snip.hxrsh.in/ubi-1648158221585

Tried to install to Lenovo Tab M10 TB-X605F
Enabled Developer mode etc
Got message that Boot-Loader unlock had failed.
After another couple of tries I realised that I was required to execute "fastboot flashing unlock".
Problem was I couldn't access a terminal app without signing in to google play store.
Didn't want to do that.

**Error:**
```
Unknown Error
```

**Comment by NeoTheThird** [comment]
The installer _should_ actually run the oem unlock for you, in case you run into a problem. That instruction in the configs is redundant and will be removed now https://github.com/ubports/installer-configs/pull/179. And for the record, the `fastboot flashing unlock` command would be run on the computer the phone is connected to, not your phone itself. But in any case, that's not the problem here. What you're experiencing is that the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
