### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.555s]booting...FAILED (remote: unknown command)finished. total time: 0.569s

### ISSUE THREAD

**Issue by shiqishao** [ubports/ubports-installer#254]
Automatically generated error report 
Versi

**Comment by NeoTheThird** [comment]
I'm gonna need some information from you ;) What device are you installing on, what is it running? What OS does your PC have? Which package and version of the Installer are you using?

**Comment by zubozrout** [comment]
@NeoTheThird Please check out this bug report: https://bugs.launchpad.net/ubports-arale/+bug/1690803 - may be relevant.

I'd guess that for MX4 a different installer policy is required. Once recovery images are flashed the installer should not try to boot them automatically but rather ask user to reboot to recovery manually and then continue perhaps upon hitting a button in the app if automatic detection is an issue - but I'd guess it is not since it already works in other parts of the installation (even with adb).

**Comment by NeoTheThird** [comment]
@zubozrout I'll look into that, thanks for the hint.

**Comment by zubozrout** [comment]
I've tried to use the ignore button there but it seems nothing is happening afterwards - that is if I manually reboot to recovery and click ignore this is all it does:
```
{"level":"info","message":"Booting into recovery image...","timestamp":"2018-10-05T21:04:06.017Z"}
{"level":"error","message":"Devices: Error: Fastboot: Unknown error:  downloading 'boot.img'...\nOKAY [  0.762s]\nbooting...\nFAILED (remote: unknown command)\nfinished. total time: 0.776s\n","timestamp":"2018-10-05T21:04:06.877Z"}
{"level":"info","message":"ERROR IGNORED","timestamp":"2018-10-05T21:08:35.983Z"}
```

**Comment by NeoTheThird** [comment]
Solved in #710. Sorry about the delay everyone...

**Comment by A2t1p1** [comment]
hola algjuien sabe como solucionar este problema?
FAILED (remote: unknown command)

**Comment by A2t1p1** [comment]
C:\Program Files (x86)\Minimal ADB and Fastboot>fastboot devices
2111e450        fastboot

C:\Program Files (x86)\Minimal ADB and Fastboot>fastboot oem unlock
...
FAILED (remote: unknown command)
finished. total time: 0.004s

siempre me da esa falla, que puedo hacer?
