### ISSUE TITLE
Please publish the ubports-installer application in the microsoft store instead of keeping it as an exe file

### ISSUE THREAD

**Issue by apy7hst** [ubports/ubports-installer#2677]
It is more secure and more productive to install apps from the microsoft store than using an exe file these days therefore, please replace the exe file with the microsoft store application, as well as package the needed drivers along with it.

**Comment by Flohack74** [comment]
I do not think that Microsoft will accept the installer. Yes, I know some PCs cannot run the installer without being digitally signed etc. For example, we need a certificate for this (and also pay for it and administer it), and we need to pass store validation, which could be a problem since we bundle adb and fastboot executables.
Also I do not think that a store App can install USB drivers needed for adb and fastboot to work, so this will alway be a manual step.
Overall I do not think there is much of a better way via store, but wee introduce another dependency for us, anbd Microsoft can anytime decide to kick us out if they do not like how we are packaging the electron app. Which I think will be very likely.
