### ISSUE TITLE
"Device not supported -- Your device:sudounabletoresolvehostubuntuphabletturbo"

### ISSUE THREAD

**Issue by wdbm** [ubports/ubports-installer#275]
Hey there

I'm observing an issue with UBports Installer `ubports-installer 0.1.13-beta` installed via snap on Ubuntu 16.04 when attempting to use it with my Meizu PRO 5, which is an international Android edition that has been wiped and repartitioned for suitability with UBports Ubuntu Touch 16.04 (and is running currently with UBports Ubuntu Touch 15.04). I have verified that adb has access to the phone.

![](https://i.imgur.com/hkTIkUj.png)

The device type "turbo" is not being picked up properly.

The terminal output on running is as follows:

```Bash
>ubports-installer 
Pug interceptor registered successfully
debug: Using native platform tools!
debug: 
debug: 
debug: adb shell: echo 1
debug: 
debug: adb shell: getprop ro.product.device
debug: 
debug: getprop: sudounabletoresolvehostubuntuphabletturbo
```

**Comment by pixelr0** [comment]
? https://github.com/ubports/ubports-installer#device-not-detected-linux

**Comment by NeoTheThird** [comment]
An Android edition Meizu Pro 5? That's interesting! I was not aware that you could even unlock those! How did you manage to do that?

The problem is that adb is not reporting a correct device id, you might have overwritten it when unlocking the bootloader with some shady method. Have you tried selecting the Meizu Pro 5 manually by klicking the button? Since the installer *can* talk to the phone (else it wouldn't get that wonky getprop answer), the installation might just continue as expected.
