### ISSUE TITLE
Fastboot: Unknown error:  [sudo] contrasenya per a elteumestre: downloading 'boot.img'...OKAY [  0.331s]booting...FAILED (remote: unknown command)finished. total time: 0.333s

### ISSUE THREAD

**Issue by elteumestre** [ubports/ubports-installer#439]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: BQ Aquaris E4.5
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/4CXyDR73C7/

**Comment by elteumestre** [comment]
Hola:
Quiero instalar Ubuntu Phone en un teléfono móvil bq 4.5 que tiene ahora Android, pero que inicialmente tenía Ubuntu Phone.
Saludos cordiales.

Manuel Martínez Segura.
imagina-ho@protonmail.com

**Comment by advocatux** [comment]
Hola, tienes que seguir estas instrucciones http://docs.ubports.com/es/latest/userguide/install.html#install-on-legacy-android-devices

Puedes unirte al grupo UBports Español en Telegram (https://t.me/UBPorts_ES) si necesitas ayuda adicional.

------------------------------------------

Hi, please follow these instructions http://docs.ubports.com/es/latest/userguide/install.html#install-on-legacy-android-devices

You can join the UBports Spanish group in Telegram (https://t.me/UBPorts_ES) if you need additional help.

**Comment by elteumestre** [comment]
Hola:

Ya descargué UBports-installer.
En la página que te enlazo, no se descarga nada.

https://www.mibqyyo.com/descargas/categorias/aquaris-e4-5-ubuntu-edition

Saludos.

http://mestreacasa.gva.es/web/martinez_man23

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by advocatux** [comment]
Si, https://github.com/ubports/docs.ubports.com/issues/133 no se ha solucionado aún pero ahí puedes ver como descargar lo que necesitas.

Podemos seguir en español en el grupo de Telegram porque el idioma oficial de los informes de errores es el inglés. Gracias.

----------------------------------------------------------------

Yes, https://github.com/ubports/docs.ubports.com/issues/133 is not fixed yet but you can see there how to download the necessary files.

We can continue this conversation in the Spanish group in Telegram because the bug tracker official language is English. Thank you.

**Comment by fabrei** [comment]
i had the same log messages. maybe [this](https://github.com/ubports/ubports-installer/issues/416#issuecomment-417250720) helps :)

**Comment by NeoTheThird** [comment]
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.
