### ISSUE TITLE
Missing build dependencies on 18.04

### ISSUE THREAD

**Issue by jonnius** [ubports/ubports-installer#521]
The setup script depends on the package **nodejs-legacy**, which is no longer in the ubuntu repos (starting from 18.04).

**Comment by Ingo-FP-Angel** [comment]
I recently (59b2a55c4a02f0c6ad45f2990f8e198e3a49bb0f) added a check to determine if the setup script is run on opensuse because they use different package names than ubuntu.

Would it be sufficient to add another check for ubuntu and its version and then use a different package?
Or are the newer nodejs packages in 18.04 generally incompatible?

**Comment by jonnius** [comment]
Thank @Ingo-FP-Angel!

**Comment by NeoTheThird** [comment]
+1
