### ISSUE TITLE
Failed with pre-flashed meizu pro 5

### ISSUE THREAD

**Issue by grandrew** [ubports/ubports-installer#548]
I tried installing on Meizu PRO 5 with older ubuntu installed. It was converted from Android before, with ubuntu bootloader

*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: unknown
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/PF73xwHcsY/

**Comment by grandrew** [comment]
@AlainW94 Thank you very much!

Of course I am interested in your solution. As I did not spend any time on this yet, I can review your patches and submit a PR

P.S. never liked the (lack of) security of fingerprint sensor anyways :-P

**Comment by AlainW94** [comment]
Hi @grandrew ,

Ok, first you will have to flash the TWRP as a rcovery image, then boot on it using VOL_UP+POWER.
Once in TWRP, go to advanced, terminal.

You will have to mount the actual linux partition where the system bin are because the fdisk coming from TWRP is too limited, we will use the one from the linux system. To do that : 
mount /dev/block/sda41 /system
mount -t proc proc /system/proc
mount -t sysfs sys /system/sys
mount -o bind /dev /system/dev
chroot /system /bin/bash

Now we will delete the custom partition and recreate a smaller one (324 Mo instead of 512Mo):

fdisk /dev/block/sda

42 is the custom partition.

input :
p (Will display the partition table)
d (delete partition)
42 (number 42)
n (create partition)
42 (number will be 42)
+324M (partition size)
x (expert mode)
n (name the partition)
custom
r (return to menu)
w (write changes to the table)

Reboot with TWRP in recovery mode again.
Then format the new partition : mke2fs -t ext4 -m 0 /dev/block/sda42

Remount the system files : 
mount /dev/block/sda41 /system
mount -t proc proc /system/proc
mount -t sysfs sys /system/sys
mount -o bind /dev /system/dev
chroot /system /bin/bash

Now we will delete and recreate a bigger cache partition (43) : 
fdisk /dev/block/sda
p (affiche la tables des partitions)
d
43
n
43 (check that the first sector is corresponding to the previous last sector (from partition 42) +1, it was good by default for me)
[ENTRER]
x
n
cache
r
w

Reboot again in recovery mode then format the cache partition : 
mke2fs -t ext4 -m 0 /dev/block/sda43

At that point, you have enough space to install the new OTA 5.

Now use the following deb file: 

https://ufile.io/ghhcs

It is the modified ubuntu-installer that I made, the only difference is that when the installer usually fail while rebooting into recovery mode after flashing the boot.img, here you will be prompted to manually reboot into recovery mode (VOL_UP+POWER) then install will download on your computer the latest files, pushing them to your device and make the device to reboot.

Please let me know if that works well for you ! Good luck ;)

**Comment by vokaliz** [comment]
Hello! Use the last ubports-installer, it must work for meizu pro 5. I have same problem on my meizu "powered by ubuntu", after my issue at github ubports-support fixed the installer. If you wish you can back life your ubuntu phone with ubports :)
