### ISSUE TITLE
Installer does not detect Fairphone 2 without sudo in 17.10

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubports-installer#60]
I've tried the following to get the installer (0.1.9) to run correctly under Ubuntu 17.10:

 - Add udev rules
 - Install fastboot and adb onto the system
 - Run the installer from the terminal with or without either of the two above options

However, the only way that I can get it to reliably detect my Fairphone is with `sudo ./ubports-installer[...].AppImage`.

I'll continue to collect reports from others with different devices.

**Comment by NeoTheThird** [comment]
Do you have more information on this? I can't imagine this is actually the case, since the installer usually runs all tools and subroutines it needs with sudo anyways. What you usually need with the Fairphone for adb is the workaround from #56, but even that should be undone by sudo.

What's your experience with the snap or deb?

**Comment by NeoTheThird** [comment]
Ok, so the installer should definitely never in any case be run with sudo. Closing unless more information will become available.
