### ISSUE TITLE
It says I have a kltevzw when I have a s6

### ISSUE THREAD

**Issue by Nikita11790** [ubports/ubports-installer#711]
*Automatically generated error report* %0D%0AUBports Installer Version: 0.1.21-beta %0D%0ADevice: kltevzw%0D%0APackage: dmg%0D%0AOperating System: macOS 10.14.318D109 x64 %0D%0ANodeJS version: v8.2.1 %0D%0A%0D%0AError log: http://paste.ubuntu.com/p/VqJCmxv2hq/ %0D%0A

It says I have a kltevzw when I have a s6

**Comment by NeoTheThird** [comment]
That is the device id/codename, a unique name for your device used by developers before the official commerical name of the device is decided. The codename remains in usage in internal components and it is how the devices identify to the installer. What is weird in this case is that kltevzw is actually the codename for the s5, not the s6. So either you have been running around with a different phone than you thought all this time or you have installed an image or recovery for the s5. At least it announces itself to the installer as such. It doesn't matter either way though, because we unfortunately do not support both of these devices at the moment. See [here](https://devices.ubuntu-touch.io) for a list of supported devices and [here](https://halium.org) if you want to look into porting yourself. Sorry we can not help you today...
