### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bootstrap' of undefined (MainRenderer:247)

### ISSUE THREAD

**Issue by badiga** [ubports/ubports-installer#729]
*Automatically generated error report* %0D%0AUBports Installer Version: 0.1.21-beta %0D%0ADevice: Nexus 6%0D%0APackage: dmg%0D%0AOperating System: macOS 10.14.318D109 x64 %0D%0ANodeJS version: v8.2.1 %0D%0A%0D%0AError log: http://paste.ubuntu.com/p/Ktc8ptP7Sh/ %0D%0A

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Due to #692, this was not properly shown in the installer. This issue is now resolved, a new version will be released shortly. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
