### ISSUE TITLE
Summary of my attempts to install Ubuntu Touch on a Nexus 5 and issues encountered

### ISSUE THREAD

**Issue by touch-ubuntu** [ubports/ubports-installer#735]
*NOT Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Linux Mint undefined undefined x64 
Note: all this occurred on 03/24/2019 and 03/25/2019

Dear Ubports, 

Thanks for your hard work on this very important project! It's nice that people care enough to keep this project going despite it being abandoned by canonical.

*************Summary of my attempts to install Ubuntu Touch on a Nexus 5************

-I tried to follow the lovely installer promotional video but it sadly ‌did not go as smoothly as that. 

-First attempts at running UT installer was on Lubuntu 16.04 LTS, wi‌th adb previously installed
(install got hung up and wouldn't proceed past getting to UBports recovery mode, multiple attempts)

-Second attempts: on a separate windows 8.1 machine, the installer failed to recognize the device in the standard android recovery mode (this part is not elaborated below) 

-Third attempts: Linux MINT 18.3 (Ubuntu 16.04 codebase) first try failed, but after reboot, it succeeded!

-I've included the below detail hoping that I can help isolate what the problems were so that they could 
be added to a list of known issues, at the least, or that perhaps the issues could be identified and fixed.
The installer is the first encounter the end-user has with running UBports code, and people with lesser motivation might not have gone as far as I did to try to get it to work. I think UT is a great project, and I would be very interested in helping identify what the issues were that I encountered; how, and what caused me to encounter them, and what I and others might be able to do to improve the end user experience. Below I go into much greater detail regarding what I've summarized above, for those who are brave enough to read a lot. 

-Thanks again for your efforts and for taking the time to read this! 

*******************end of summary*******************

This next part is gives more specific details:

I have recently successfully installed UT 16.04 stable on a nexus 5 device via the deb installer package: 

ubports-installer_0.1.21-beta_amd64.deb

But it didn't go quite as smoothly as depicted in this ubports install video 
(excellent production value on that video btw, cheers to that!) 

Ubuntu Touch Install video 2018
https://www.youtube.com/watch?v=zuLFTGkuD68  

I attempted to follow the video almost exactly 
(ubuntu computer installer host was a 2008/2009 intel macbook with usb 2.0 ports)
(though I ran the installer in lubuntu 16.04, rather than standard ubuntu)

I figured since lubuntu has the official blessing
of canonical it should be fine, right?

The full OS details are here: 

  Operating System: Ubuntu 16.04.4 LTS
                    Kernel: Linux 4.4.0-128-generic
            Architecture: x86-64

'adb version' reports: 
Android Debug Bridge version 1.0.32
Revision debian

I followed the ubports video exactly --- The refurbished nexus 5 had come with android 6.0.0 build MRA58K, and I may have upgraded it once or twice (either to 6.0.0 MRA58N, or 6.0.1 MMB29K) 

I do not believe that I had enabled developer mode in android, but the 
video made no mention of dev mode, so I guess I may have assumed (wrongly?) 
that it didn't matter. Anyway, here's what I did: 

-started the installer
-attached to phone with USB cable
-selected 'Nexus 5' and 'wipe'
-entered password
-booted phone to recovery mode
-installer asked to unlock bootloader and I confirmed it on phone
-2 files were downloaded (not sure about the placement in the order that this occurred)
-files pushed to phone

at this point, I left the room. When I returned much later, the phone
had the 'google' bootscreen with an open padlock (I assume meaning unlocked bootloader), and the installer did not appear to be doing anything...the installer said something like 'waiting to enter recovery mode' and it was just sitting there. I went away again and I'm not sure how long I waited (less than 1 hr)..but ultimately it appeared to be hung. 

At first I was concerned that I was in some kind of bootloop but managed to get back to recovery mode and power down the phone. I closed everything down and decided to try again the next day. 

The next day I managed to get back to the recovery menu and ran the software again, and things went fine up until a similar point, installer waiting to enter recovery mode, even though the phone actually seemed to have made it to the UBports recovery menu. I tried several more variants of this, no luck. 

I checked around in the ubports forums, and found a post that seemed to indicate the presence of adb and fastboot files in /usr/bin folder were critical to the installer running successfully:

'I can see adb (137.5kb) and fastboot(93.1kb) files in /usr/bin/.'
https://forums.ubports.com/topic/1333/nexus-5-install-file-push-fail

so I checked those files, and I discovered that while I did have both of 
those files, the size of adb was very wrong (~37 bytes)... 

I got the impression that file was some kind of shortcut rather than the actual file. I had indeed previously installed android debug bridge through the official ubuntu repository (sudo apt-get install adb) previous to installing the ubports installer, my intuition was telling me there might be some kind of adb version conflict (?), so I decided to try it on another distro I had previously installed: Mint 18.3 

 Mint 18.3 (compatible with Ubuntu 16.04 codebase/repos) 

 Operating System: Linux Mint 18.3
                   Kernel: Linux 4.10.0-38-generic
          Architecture: x86-64

After I completed ubports installer installation, 
at CLI 'adb version' reported:

Android Debug Bridge version 1.0.32

These are the differences between this mint attempt and the earlier lubuntu attempt:

-this version of adb is 1.0.32 but is not 'revision debian' 
-I also checked the size of the adb file in /usr/bin and it reported 161 kb, so this is the real file, not 37 bytes as in lubuntu. 
-different kernel versions (Lubuntu: Linux 4.4.0-128-generic; Mint: Linux 4.10.0-38-generic) 

in theory these are otherwise both Ubuntu 16.04 LTS distros. 

When I first installed the ubports installer and ran it in Mint, I got some kind
of visual progress bar bug, and later the installer reported an error and asked to ignore or restart the program. I opted to quit and reboot. 

After rebooting, I tried the installer again, and made it as far as the UBports recovery menu, and one might
have thought it was hung except that the installer reported that it was downloading the 12 files. 

So the installer did finish successfully, and everyth‌ing seems to be working in UT! Thanks again for building this product! 

I'm curious, are there any known issues that you see with anything I did above in lubuntu? is it the lower kernel version? the different adb version, or something else? 

Thanks again! 

-New UT user + maybe project contributor?

**Comment by NeoTheThird** [comment]
Thank you for the detailed report! If all users put that much effort into bug-reports, our work would be a lot easier. Thanks for that! Looks like you ran into multiple issues we currently have there.

We need to edit the video a little and add information about all the special situations the users might be in that require additional steps. What makes development of a user-friendly installer so difficult is that every device behaves a little differently. Every operating system installed on the device before adds extra complexity. The installer video should actually mention that the user needs to read all information in the installer carefully and follow the instructions there, hinting to possible required steps. For example, not every device can reboot automatically from fastboot mode to recovery, so the users are sometimes required to perform actions on the device during the installation.

We're actually just about to release a new version of the UBports Installer that resolves many of the usability issues you described here. It's not 100% ready yet, as we have some issues with the deb package, but you can find [the current prerelease on the releases page](https://github.com/ubports/ubports-installer/releases/tag/0.2.2-beta). Testing results have been very promising so far and we reduced the number of open issues on this repository from more than 400 to 55 in the last three weeks.

As to the adb and fastboot version conflicts you describe here, we will have to look into that. The installer also comes with its own version of adb and fastboot packaged that it can use as a fallback, maybe we should just prefer that over the ones installed on the users pc natively. Right now, the priority order goes like this: First, the installer checks if the user specified custom adb or fastboot executables in the installation options, if that's not the case, the installer checks for `adb` and `fastboot` in `$PATH`. Last resort is the fallback tools packaged with the installer. In the prerelease, you can also specify the `--force-fallback` flag to always use the fallback tools. Let's keep this issue open to think about that :)

> New UT user + maybe project contributor?

That's great! Is there anything you're particularly interested in / special skills you have? Since you already spent some time thinking about the installer, maybe you'd be interested in some of our [good first issues](https://github.com/ubports/ubports-installer/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)? Only if you know some JavaScript of course ;) There's also lots of other areas where UBports can always use help, and not everything requires programming knowledge. Here's [our get involved page](https://ubports.com/community/get-involved), if you're interested. Judging from your bug report, i can definitely say that i'd appreciate having you on the [QA team](https://docs.ubports.com/en/latest/contribute/quality-assurance.html) :)

Thanks for being a part of the UBports Community!

**Comment by touch-ubuntu** [comment]
Hi Jan,

Thank you so much for your prompt and detailed response! 
While I am guessing that adb could have played a role in my difficulties, is there a 
way to show definitively that it did? Is there some log file that was generated that 
would be helpful? 

Amusingly, when I tried to click 'bug report' in the installer on Lubuntu, the button 
was frozen and would not generate a bug report...is there some location where such 
logfiles might be saved to the disk? If those exist and are available, would they be 
helpful to you? (also, if they exist in the windows installer, where could I find them?)

In order to arrive at a github bug report page, I had originally clicked the 'bug 
report' button in the installer in Mint. Though the 2nd install attempt in Mint was ultimately 
successful, the first one in Mint was not. Whatever the issue was in the first attempt, it was fixed 
with a reboot. (See pastebin logs for those 2 Mint attempts at the end of this message) 

So ironically instead of a bug report for the completely failed attempts, so far I have one for an attempt that actually succeeded!...(and one for an attempt that probably won't help resolve the main issues I previously described...)  

Before committing to anything long-term, perhaps I could be of most immediate help in 
in resolving any outstanding issues I encountered here with the installer on the 3 OS 
versions I tried. Perhaps comparing the attempts in Lubuntu, Windows 8.1, and the ultimately 
successful attempt in Linux MINT would be useful? 

I have some experience with light python data analysis, as well as messing around with 
linux. More recently, I've started writing some C++. I've written some bash scripts as 
well. I'd be happy to go into more detail in a different setting. 

If some of the issues I encountered have already been resolved, which ones? 
In relation to the issues with the installer that I encountered, I'm quite curious about the answers to these questions:


-Did the linux kernel version matter? 
-Did the android version matter? 
-Did the adb or fastboot version matter? 
-Did the lack of activation of dev mode/android debugging in the android OS impact anything?
-Did the fact that I had already completed a partial installation via Lubuntu influence 
the complete failure of the windows installer to even detect the phone in android recovery mode? 
-Could something else that I haven't even guessed at been the cause of the issues? 

If I can, I'd like to help answer any of these questions that are not yet resolved!


PS You might want too pass this next paragraph on to whatever group is responsible for that video ------>  I know that video editing can be quite cumbersome and time consuming, especially if audio editing is also involved. Like I said, the production value (IE the cuts, the quality, the timing with the music, etc) is very very good. Reworking that is likely to be very time-consuming. It might be better to leave the video as-is for now, or only modify it slightly.  If you're looking for a fast and effective fix, I noticed that the youtube video I mentioned before does not have ANYTHING in the description. If you simply include text at the beginning and end of the video that says "Be sure to check the description below for more details!!!" and then include relevant instructions and links there. Annotations are also good though some users might have those turned off. The video I'm talking about is this one: 
Ubuntu Touch Install video 2018 - https://www.youtube.com/watch?v=zuLFTGkuD68

-----FIRST LINUX MINT 18.3 ATTEMPT (FAILED INSTALL)-----

*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/krRdKpyTyd/ 

--------------------------------------------------------------

--SECOND LINUX MINT 18.3 ATTEMPT (SUCCESSFUL AFTER REBOOT)----

*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/WGB9Qmks7X/ 

---------------------------------------------------------
