### ISSUE TITLE
Adb push error: Error: Command failed: /var/folders/lx/h18xjcpj6vj08xxs4npcym000000gp/T/.com.ubports.installer.LA9G4L -P 5038 push /Users/xujian/Library/Caches/ubports/pool/ubports-b2daf85c2a255a0affc93d808e709697e472777de4bc189dd9128211db551469.tar.xz /cache/recovery/, stdout: [...]e709697e472777de4bc189dd9128211db551469.tar.xz': remote No space left on device/Users/xujian/Library/Caches/ubports/pool/ubports-b2daf85c2a255a0affc93d808e709697e472777de4bc189dd9128211db551469.tar.xz: 0 files pushed. 4.9 MB/s (72015272 bytes in 13.941s), stderr: 

### ISSUE THREAD

**Issue by wailoonho** [ubports/ubports-installer#775]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: flo
Channel: ubports-touch/16.04/stable
Package: dmg
Operating System: macOS 10.14.418E226 x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/dGPYNQBw9S/

**Comment by 1Mike1** [comment]
please flash your device with stock ROM, this error mainly occurs due to insufficient space in cache partition. So make sure you cache partition should have space more than 400mb. Please check the details of memory using "df -a" command in terminal .. it will show you the memory block of the device. Just check the size of your cache partition if it is less then 400mb probably cache partition is the main reason of an above issue.

**Comment by pi0** [comment]
Same for Nexus7 2013 (flo). Cache partition size is around 70MB and there seems no easy way to resize it. I'm wondering why data partition is not being used or at least an option to prefer using data to copy recovery data.

(very sad. Coming back after 3 years to try out the latest version of ubuntu touch and installation is failing)

**Comment by wailoonho** [comment]
Yes, I do have the same thought. It is very difficult to resize the cache.

**Comment by pi0** [comment]
@NeoTheThird :( At least leave a statement, please.

**Comment by NeoTheThird** [comment]
Sorry, duplicate of #615
