### ISSUE TITLE
\n

### ISSUE THREAD

**Issue by iobates** [ubports/ubports-installer#887]
*Automatically generated error report* 
UBports Installer Version: 0.2.7-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: AppImage
Operating System: Manjaro Linux 18.0.4 illyria x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/kDr2njnR2c/ 
==
This occurs when I have already unlocked my device and it claims it is still locked.
I even tried to lock the phone (oem lock), then it first gives me the option to unlock and then it does this again.

**Comment by NeoTheThird** [comment]
Hey there, sorry you're having such a hard time. Hmm, that error is pretty much useless: `error 2019-09-21T10:07:41.955Z Devices: Error: undefined`. No idea what's going on. But in this one it did not ask you to oem-unlock, did it? Because i don't see that in the log...

I am not sure, but you might have an issue with sudo. If you want, you can try running the installer with `--no-root`, which will not present you with the password prompt.
