### ISSUE TITLE
Error: Unknown: error: {"killed":false,"code":3221225781,"signal":null,"cmd":"C:\\Users\\janka\\AppData\\Roaming\\ubports\\platform-tools\\adb -P 5037 kill-server"}

### ISSUE THREAD

**Issue by epierre3** [ubports/ubports-installer#911]
*Automatically generated error report* 
UBports Installer Version: 0.3.1-beta 
Device: Not detected
Channel: Not yet set
Package: exe
Operating System: Microsoft Windows [Version 10.0.17134.1006] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/fM3jpDT2xC/

**Comment by NeoTheThird** [comment]
Now that's just weird. Adb executable dies without any error. I know it's not a general windows installer issue, since i had success reports for 0.3.1-beta... Is it just adb kill-server that's failing, or does the install continue after that? Have you tried weather a device is detected if you dismiss the error?

I suppose we could catch and ignore any errors on kill-server, but if it also fails after that, we have a problem.

**Comment by epierre3** [comment]
Hi Jan,

I will continue testing, but have a lot of other stuff ongoing.
I keep you posted.

Cheers,
Ewald

Op za 5 okt. 2019 om 16:55 schreef Jan Sprinz <notifications@github.com>:

**Comment by NeoTheThird** [comment]
No pressure, whenever you get to it. For all i know 0.3.2-beta is significantly less broken on windows than its predecessors, so this does not have to concern us too much and it won't halt release. Yours is the only case this happened i know of so far.
