### ISSUE TITLE
Error: systemimage: Push failed: Failed push: Failed to push file 0: Push failed: error: {"killed":false,"code":1,"signal":null,"cmd":"/home/cm-t/.cache/ubports/platform-tools/adb -P 5037 push \"/home/cm-t/.cache/ubports/pool/ubports-8832267993eb0215232c953d6c5fa7f22ab2fe348b4e68946b098b6bdc19830c.tar.xz\" /cache/recovery/ > /dev/null"}

### ISSUE THREAD

**Issue by cm-t** [ubports/ubports-installer#936]
*Automatically generated error report* 
UBports Installer Version: 0.4.0-beta 
Device: krillin
Channel: ubports-touch/16.04/stable
Package: AppImage
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/hKb8Wd3zb4/ 

 * Now trying with option `-v` (because this bug report is in the continuing try after bug #935 ):

 * Same issue with **stable**, **devel**, **rc** (not edge).
 * I first tryed with **edge** channel 3 times: the installer didn't announced any error, it even finished with success. But the first device's boot never finished _(a full night from 00:00 to 08:00 i meant)_
 * same wire used with success with both mako (edge) &  arale (edge) install with the same build of the installer

**Comment by NeoTheThird** [comment]
Okay, thanks for trying again. So the but is somewhere in the systemimageinstall step on calling adb.pushArray() on the files from the systemimageserver. That function takes in the files the system image server as an argument, so it is possible that the step fails for some channels (stable, devel, rc) and works for others (edge), but that's very weird and should not happen. There might be some malformed data on the systemimageserver, which would be a big problem.

Another thing we see here is that there is an unhandled promise rejection, so that needs to be hunted down! All promises need a catch block.

To rule out one thing, can you reboot your phone to recovery for me, drop into `adb shell` and run `rm -rf /cache/recovery` and try again? Might be that there's some funky stuff going on with an old commandfile or something, which would cause the recovery to do weird things.
